name: Release and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'azure-appservice/**'

jobs:
  release:
    name: Relase
    runs-on: ubuntu-24.04
    environment: release
    permissions:
      contents: read
      issues: write
      packages: write
    outputs:
      new_release_published: ${{ steps.release.outputs.new_release_published }}
      new_release_version: ${{ steps.release.outputs.new_release_version }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Release
        id: release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 24.2.0
          extra_plugins: |
            @semantic-release/release-notes-generator@14.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build_push
        uses: docker/build-push-action@v6
        with:
          context: azure-appservice
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/${{ github.repository }}/azure-appservice:latest
            ghcr.io/${{ github.repository }}/azure-appservice:${{ steps.release.outputs.new_release_version }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}

  deploy-dev:
    name: Deploy Dev
    runs-on: ubuntu-24.04
    environment: dev
    needs: [release]
    if: ${{ needs.release.outputs.new_release_published }} == 'true'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Deploy to Staging Slot
        uses: azure/webapps-deploy@v3
        with:
          resource-group-name: ${{ vars.RESOURCE_GROUP_NAME }}
          app-name: ${{ vars.APP_NAME }}
          images: |
            ghcr.io/${{ github.repository }}/azure-appservice:${{ needs.release.outputs.new_release_version }}
          slot-name: staging

      - name: Swap Staging and Production Slots
        run: |
          az webapp deployment slot swap \
            -g ${{ vars.RESOURCE_GROUP_NAME }} \
            -n ${{ vars.APP_NAME }} \
            --slot staging \
            --target-slot production

  deploy-prod:
    name: Deploy Prod
    runs-on: ubuntu-24.04
    environment: fakeprod
    needs: [release, deploy-dev]
    if: ${{ needs.release.outputs.new_release_published }} == 'true'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Azure Login
        uses: azure/login@6c251865b4e6290e7b78be643ea2d005bc51f69a # v2.1.1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Deploy to Staging Slot
        uses: azure/webapps-deploy@de617f46172a906d0617bb0e50d81e9e3aec24c8 # v3.0.1
        with:
          resource-group-name: ${{ vars.RESOURCE_GROUP_NAME }}
          app-name: ${{ vars.APP_NAME }}
          images: |
            ghcr.io/${{ github.repository }}/azure-appservice:${{ needs.release.outputs.new_release_version }}
          slot-name: staging

      - name: Swap Staging and Production Slots
        run: |
          az webapp deployment slot swap \
            -g ${{ vars.RESOURCE_GROUP_NAME }} \
            -n ${{ vars.APP_NAME }} \
            --slot staging \
            --target-slot production
